language: go
go: 1.12
env:
  - GO111MODULE=on
services:
  - docker
deploy:
  skip_cleanup: true
  provider: script
  script: bash push_docker_backend
  on:
    branch: Deploy
script:
  - chmod 600 ./2019_1_SleeplessNights_id_rsa.pem
  - ssh-keyscan -H 89.208.198.186 >> ~/.ssh/known_hosts
  - scp -i ./2019_1_SleeplessNights_id_rsa.pem -r ../2019_1_SleeplessNights ubuntu@89.208.198.186:/home/ubuntu/Deploy/Backend
branches:
  only:
  - Deploy
before_install:
  - openssl aes-256-cbc -K $encrypted_d7dce7d88d63_key -iv $encrypted_d7dce7d88d63_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar
