// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionToken) Reset()         { *m = SessionToken{} }
func (m *SessionToken) String() string { return proto.CompactTextString(m) }
func (*SessionToken) ProtoMessage()    {}
func (*SessionToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *SessionToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionToken.Unmarshal(m, b)
}
func (m *SessionToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionToken.Marshal(b, m, deterministic)
}
func (m *SessionToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionToken.Merge(m, src)
}
func (m *SessionToken) XXX_Size() int {
	return xxx_messageInfo_SessionToken.Size(m)
}
func (m *SessionToken) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionToken.DiscardUnknown(m)
}

var xxx_messageInfo_SessionToken proto.InternalMessageInfo

func (m *SessionToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserSignature struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSignature) Reset()         { *m = UserSignature{} }
func (m *UserSignature) String() string { return proto.CompactTextString(m) }
func (*UserSignature) ProtoMessage()    {}
func (*UserSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSignature.Unmarshal(m, b)
}
func (m *UserSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSignature.Marshal(b, m, deterministic)
}
func (m *UserSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSignature.Merge(m, src)
}
func (m *UserSignature) XXX_Size() int {
	return xxx_messageInfo_UserSignature.Size(m)
}
func (m *UserSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSignature.DiscardUnknown(m)
}

var xxx_messageInfo_UserSignature proto.InternalMessageInfo

func (m *UserSignature) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserSignature) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarPath           string   `protobuf:"bytes,4,opt,name=avatarPath,proto3" json:"avatarPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetAvatarPath() string {
	if m != nil {
		return m.AvatarPath
	}
	return ""
}

type NewUserData struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserData) Reset()         { *m = NewUserData{} }
func (m *NewUserData) String() string { return proto.CompactTextString(m) }
func (*NewUserData) ProtoMessage()    {}
func (*NewUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *NewUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserData.Unmarshal(m, b)
}
func (m *NewUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserData.Marshal(b, m, deterministic)
}
func (m *NewUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserData.Merge(m, src)
}
func (m *NewUserData) XXX_Size() int {
	return xxx_messageInfo_NewUserData.Size(m)
}
func (m *NewUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserData.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserData proto.InternalMessageInfo

func (m *NewUserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUserData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewUserData) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type PageData struct {
	Since                uint64   `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageData) Reset()         { *m = PageData{} }
func (m *PageData) String() string { return proto.CompactTextString(m) }
func (*PageData) ProtoMessage()    {}
func (*PageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *PageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageData.Unmarshal(m, b)
}
func (m *PageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageData.Marshal(b, m, deterministic)
}
func (m *PageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageData.Merge(m, src)
}
func (m *PageData) XXX_Size() int {
	return xxx_messageInfo_PageData.Size(m)
}
func (m *PageData) XXX_DiscardUnknown() {
	xxx_messageInfo_PageData.DiscardUnknown(m)
}

var xxx_messageInfo_PageData proto.InternalMessageInfo

func (m *PageData) GetSince() uint64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *PageData) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type LeaderBoardPage struct {
	Leaders              []*Profile `protobuf:"bytes,1,rep,name=leaders,proto3" json:"leaders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LeaderBoardPage) Reset()         { *m = LeaderBoardPage{} }
func (m *LeaderBoardPage) String() string { return proto.CompactTextString(m) }
func (*LeaderBoardPage) ProtoMessage()    {}
func (*LeaderBoardPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *LeaderBoardPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderBoardPage.Unmarshal(m, b)
}
func (m *LeaderBoardPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderBoardPage.Marshal(b, m, deterministic)
}
func (m *LeaderBoardPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderBoardPage.Merge(m, src)
}
func (m *LeaderBoardPage) XXX_Size() int {
	return xxx_messageInfo_LeaderBoardPage.Size(m)
}
func (m *LeaderBoardPage) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderBoardPage.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderBoardPage proto.InternalMessageInfo

func (m *LeaderBoardPage) GetLeaders() []*Profile {
	if m != nil {
		return m.Leaders
	}
	return nil
}

type Profile struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	WinRate              float32  `protobuf:"fixed32,2,opt,name=winRate,proto3" json:"winRate,omitempty"`
	Rating               uint32   `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Matches              uint32   `protobuf:"varint,4,opt,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Profile) GetWinRate() float32 {
	if m != nil {
		return m.WinRate
	}
	return 0
}

func (m *Profile) GetRating() uint32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Profile) GetMatches() uint32 {
	if m != nil {
		return m.Matches
	}
	return 0
}

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type UserId struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*SessionToken)(nil), "services.SessionToken")
	proto.RegisterType((*UserSignature)(nil), "services.UserSignature")
	proto.RegisterType((*User)(nil), "services.User")
	proto.RegisterType((*NewUserData)(nil), "services.NewUserData")
	proto.RegisterType((*PageData)(nil), "services.PageData")
	proto.RegisterType((*LeaderBoardPage)(nil), "services.LeaderBoardPage")
	proto.RegisterType((*Profile)(nil), "services.Profile")
	proto.RegisterType((*Nothing)(nil), "services.Nothing")
	proto.RegisterType((*UserId)(nil), "services.UserId")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x6b, 0xdb, 0x4e,
	0x10, 0x8d, 0x65, 0xfd, 0x2c, 0x7b, 0xfc, 0x73, 0xda, 0x2e, 0x6d, 0xaa, 0xea, 0x50, 0xc2, 0xd2,
	0x43, 0xa0, 0x60, 0xa8, 0x4b, 0x73, 0x0c, 0xd4, 0x4e, 0x31, 0x86, 0x26, 0x18, 0xb9, 0x39, 0xf5,
	0x34, 0x95, 0xa6, 0xd6, 0x62, 0x59, 0x32, 0xbb, 0x9b, 0x98, 0x7c, 0xc5, 0x7e, 0xaa, 0xb2, 0x2b,
	0x29, 0x52, 0xe4, 0xa6, 0xd0, 0x9b, 0xdf, 0xfc, 0x79, 0xef, 0xad, 0xe6, 0x61, 0x80, 0x5b, 0x45,
	0x72, 0xbc, 0x93, 0xb9, 0xce, 0x59, 0x5f, 0x91, 0xbc, 0x13, 0x11, 0x29, 0xfe, 0x0e, 0xfe, 0x5f,
	0x91, 0x52, 0x22, 0xcf, 0xbe, 0xe5, 0x1b, 0xca, 0xd8, 0x4b, 0xf8, 0xcf, 0xfe, 0xf0, 0x3b, 0xa7,
	0x9d, 0xb3, 0x41, 0x58, 0x00, 0xfe, 0x19, 0x46, 0x37, 0x8a, 0xe4, 0x4a, 0xac, 0x33, 0xd4, 0xb7,
	0x92, 0xcc, 0x18, 0x6d, 0x51, 0xa4, 0xd5, 0x98, 0x05, 0x2c, 0x80, 0xfe, 0x0e, 0x95, 0xda, 0xe7,
	0x32, 0xf6, 0x1d, 0xdb, 0x78, 0xc0, 0x3c, 0x01, 0xd7, 0x50, 0xb0, 0x63, 0x70, 0x44, 0x6c, 0xd7,
	0xdc, 0xd0, 0x11, 0x71, 0xcd, 0xe4, 0xb4, 0x98, 0x32, 0x11, 0x6d, 0x32, 0xdc, 0x92, 0xdf, 0x2d,
	0x98, 0x2a, 0xcc, 0xde, 0x02, 0xe0, 0x1d, 0x6a, 0x94, 0x4b, 0xd4, 0x89, 0xef, 0xda, 0x6e, 0xa3,
	0xc2, 0xbf, 0xc3, 0xf0, 0x9a, 0xf6, 0x46, 0xec, 0x12, 0x35, 0xfe, 0xbb, 0xd5, 0xbf, 0x89, 0xf3,
	0x73, 0xe8, 0x2f, 0x71, 0x4d, 0x15, 0xb3, 0x12, 0x59, 0x44, 0xe5, 0x6b, 0x0a, 0x60, 0xaa, 0xa9,
	0xd8, 0x0a, 0x6d, 0x69, 0xdd, 0xb0, 0x00, 0xfc, 0x02, 0x9e, 0x7d, 0x25, 0x8c, 0x49, 0x4e, 0x73,
	0x94, 0xb1, 0xa1, 0x60, 0xef, 0xc1, 0x4b, 0x6d, 0x49, 0xf9, 0x9d, 0xd3, 0xee, 0xd9, 0x70, 0xf2,
	0x62, 0x5c, 0x9d, 0x65, 0xbc, 0x94, 0xf9, 0x4f, 0x91, 0x52, 0x58, 0x4d, 0xf0, 0x7b, 0xf0, 0xca,
	0x1a, 0xe3, 0xe0, 0x9a, 0x53, 0x5a, 0xd5, 0xe1, 0xe4, 0xb8, 0x5e, 0x32, 0x4f, 0x0e, 0x6d, 0x8f,
	0xf9, 0xe0, 0xed, 0x45, 0x16, 0xa2, 0x26, 0x6b, 0xc3, 0x09, 0x2b, 0xc8, 0x4e, 0xa0, 0x27, 0x51,
	0x8b, 0x6c, 0x6d, 0x9f, 0x36, 0x0a, 0x4b, 0x64, 0x36, 0xb6, 0xa8, 0xa3, 0x84, 0x94, 0xfd, 0xa4,
	0xa3, 0xb0, 0x82, 0x7c, 0x00, 0xde, 0x75, 0xae, 0x13, 0x91, 0xad, 0xb9, 0x0f, 0x3d, 0x23, 0xb2,
	0x88, 0xdb, 0x67, 0x9c, 0xfc, 0xea, 0x16, 0xad, 0xab, 0x15, 0x3b, 0x07, 0x98, 0x25, 0x14, 0x6d,
	0x8a, 0x40, 0x9d, 0xd4, 0xfe, 0x9a, 0x41, 0x0b, 0x5a, 0xbe, 0xf9, 0x11, 0xbb, 0x80, 0xc1, 0x15,
	0x6e, 0xa8, 0x58, 0x7b, 0xfd, 0xb8, 0xfd, 0x90, 0xbc, 0xe0, 0x09, 0x3e, 0x7e, 0xc4, 0x3e, 0x01,
	0xcc, 0x24, 0xa1, 0x26, 0x9b, 0xb3, 0x57, 0xf5, 0x5c, 0x23, 0x0d, 0x7f, 0x90, 0xfd, 0x00, 0x30,
	0x27, 0x5d, 0x7d, 0xdc, 0x56, 0x3f, 0x38, 0xbc, 0x89, 0x5d, 0x19, 0xdd, 0xec, 0x62, 0xd4, 0xf4,
	0xd4, 0xd6, 0xa1, 0xca, 0x17, 0x60, 0x73, 0xd2, 0xed, 0x08, 0xb0, 0x06, 0x7b, 0x99, 0xaa, 0xe0,
	0x4d, 0x5d, 0x6b, 0x8d, 0x5b, 0x65, 0x6f, 0x96, 0x12, 0xca, 0xcb, 0x29, 0x6b, 0x38, 0x2b, 0xcf,
	0x13, 0x1c, 0x96, 0xec, 0xca, 0x70, 0x4e, 0xda, 0xd8, 0x98, 0xde, 0x2f, 0x62, 0xf6, 0xfc, 0xb1,
	0xb5, 0x45, 0x7c, 0x68, 0xf6, 0x47, 0xcf, 0xfe, 0x4b, 0x7c, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x70, 0xd6, 0x6d, 0x1b, 0x33, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserMSClient is the client API for UserMS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserMSClient interface {
	CheckToken(ctx context.Context, in *SessionToken, opts ...grpc.CallOption) (*User, error)
	MakeToken(ctx context.Context, in *UserSignature, opts ...grpc.CallOption) (*SessionToken, error)
	CreateUser(ctx context.Context, in *NewUserData, opts ...grpc.CallOption) (*User, error)
	GetProfile(ctx context.Context, in *User, opts ...grpc.CallOption) (*Profile, error)
	UpdateProfile(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	GetLeaderBoardPage(ctx context.Context, in *PageData, opts ...grpc.CallOption) (*LeaderBoardPage, error)
	ClearDB(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Nothing, error)
	GetUserById(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error)
}

type userMSClient struct {
	cc *grpc.ClientConn
}

func NewUserMSClient(cc *grpc.ClientConn) UserMSClient {
	return &userMSClient{cc}
}

func (c *userMSClient) CheckToken(ctx context.Context, in *SessionToken, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/services.UserMS/CheckToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMSClient) MakeToken(ctx context.Context, in *UserSignature, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/services.UserMS/MakeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMSClient) CreateUser(ctx context.Context, in *NewUserData, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/services.UserMS/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMSClient) GetProfile(ctx context.Context, in *User, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/services.UserMS/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMSClient) UpdateProfile(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/services.UserMS/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMSClient) GetLeaderBoardPage(ctx context.Context, in *PageData, opts ...grpc.CallOption) (*LeaderBoardPage, error) {
	out := new(LeaderBoardPage)
	err := c.cc.Invoke(ctx, "/services.UserMS/GetLeaderBoardPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMSClient) ClearDB(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/services.UserMS/ClearDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMSClient) GetUserById(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/services.UserMS/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserMSServer is the server API for UserMS service.
type UserMSServer interface {
	CheckToken(context.Context, *SessionToken) (*User, error)
	MakeToken(context.Context, *UserSignature) (*SessionToken, error)
	CreateUser(context.Context, *NewUserData) (*User, error)
	GetProfile(context.Context, *User) (*Profile, error)
	UpdateProfile(context.Context, *User) (*User, error)
	GetLeaderBoardPage(context.Context, *PageData) (*LeaderBoardPage, error)
	ClearDB(context.Context, *Nothing) (*Nothing, error)
	GetUserById(context.Context, *UserId) (*User, error)
}

// UnimplementedUserMSServer can be embedded to have forward compatible implementations.
type UnimplementedUserMSServer struct {
}

func (*UnimplementedUserMSServer) CheckToken(ctx context.Context, req *SessionToken) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToken not implemented")
}
func (*UnimplementedUserMSServer) MakeToken(ctx context.Context, req *UserSignature) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeToken not implemented")
}
func (*UnimplementedUserMSServer) CreateUser(ctx context.Context, req *NewUserData) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserMSServer) GetProfile(ctx context.Context, req *User) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (*UnimplementedUserMSServer) UpdateProfile(ctx context.Context, req *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (*UnimplementedUserMSServer) GetLeaderBoardPage(ctx context.Context, req *PageData) (*LeaderBoardPage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderBoardPage not implemented")
}
func (*UnimplementedUserMSServer) ClearDB(ctx context.Context, req *Nothing) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearDB not implemented")
}
func (*UnimplementedUserMSServer) GetUserById(ctx context.Context, req *UserId) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}

func RegisterUserMSServer(s *grpc.Server, srv UserMSServer) {
	s.RegisterService(&_UserMS_serviceDesc, srv)
}

func _UserMS_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMSServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.UserMS/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMSServer).CheckToken(ctx, req.(*SessionToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMS_MakeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSignature)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMSServer).MakeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.UserMS/MakeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMSServer).MakeToken(ctx, req.(*UserSignature))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMS_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMSServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.UserMS/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMSServer).CreateUser(ctx, req.(*NewUserData))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMS_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMSServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.UserMS/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMSServer).GetProfile(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMS_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMSServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.UserMS/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMSServer).UpdateProfile(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMS_GetLeaderBoardPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMSServer).GetLeaderBoardPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.UserMS/GetLeaderBoardPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMSServer).GetLeaderBoardPage(ctx, req.(*PageData))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMS_ClearDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMSServer).ClearDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.UserMS/ClearDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMSServer).ClearDB(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMS_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMSServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.UserMS/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMSServer).GetUserById(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserMS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.UserMS",
	HandlerType: (*UserMSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckToken",
			Handler:    _UserMS_CheckToken_Handler,
		},
		{
			MethodName: "MakeToken",
			Handler:    _UserMS_MakeToken_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserMS_CreateUser_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _UserMS_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _UserMS_UpdateProfile_Handler,
		},
		{
			MethodName: "GetLeaderBoardPage",
			Handler:    _UserMS_GetLeaderBoardPage_Handler,
		},
		{
			MethodName: "ClearDB",
			Handler:    _UserMS_ClearDB_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _UserMS_GetUserById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
